---
title: "Raster Statistics"
author: "Baris Uzel"
date: "April 8, 2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Statistics from Rasters


Load Libraries

```{r}
library(dplyr)
library(tidyr)
library(gstat)
library(rgdal)
library(raster)
library(rasterVis)
library(lattice)
library(sf)
library(ggplot2)
options(stringsAsFactors = FALSE)
```

Load Raster
```{r}
DEM <- raster("Data/cuyama_DEM.tif")  # read raster
DEM <- setMinMax(DEM)
```
Prepare attribute table and shapefile
```{r}
cdata <- read.csv("Data/Cuyama.csv")
str(cdata)

#prepare attributes
cstats <- dplyr::select(cdata,site,lat,long,shrub.ID,x,y,z,measure,treatment,sensor,microsite)
refined <- distinct(cstats,shrub.ID,sensor,treatment,site,lat,long,x,y,z,microsite)
rcstats <-mutate(refined, Volume=(2/3)*pi*(x/2)*(y/2)*z)

#convert to spatial data
shrubpoints <- st_as_sf(rcstats, coords = c("long", "lat"), crs = "+proj=longlat +ellps=WGS84 +datum=WGS84 +units=degrees +no_defs") #4326 is the WGS coordinate system
st_crs(shrubpoints) #our data is now georeferenced
class(shrubpoints)


UTMshrubs <- st_transform(shrubpoints, CRS("+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +towgs84=0,0,0")) # I can't get this code to transform CRS's correctly
  #"+proj=utm +zone=11 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +towgs84=0,0,0"))
  #"+init=epsg:2455"))
st_transform(rcstats, CRS("+init=epsg:2455"))


st_write(shrubpoints, "Data/shrubstats.shp", driver = "ESRI Shapefile") #export the shapefile

```

Convert to UTM as an alternative
```{r}
DEMutm <- projectRaster(DEM, 
                            crs="+proj=utm +zone=11 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0")
cellStats(DEMutm, min)
cellStats(DEMutm, max)
DEMutm@extent
plot(DEMutm,
     main="Elevation")

UTM <- st_crs(DEMutm)
```




Regression
```{r}
slope <- terrain(DEMutm, opt = 'slope', unit = 'degrees')  #calculate slope in case we wanna use them
aspect <- terrain(DEMutm, opt = 'aspect', unit = 'degrees') #calculate aspect in case we wanna use them
topography <- stack(DEMutm,slope, aspect)


shrubbuffer <-raster::extract(topography,
                      UTMshrubs,
                      buffer = 100,
                      fun = mean,
                      sp = TRUE) # For every site this creates a 100m buffer and takes the average elevation, slope and aspect
summary(shrubbuff2)
summary(shrubbuffer)
par(mfrow = c(1, 1)) #set the frame back to 1x1
plot(DEMutm,
     main="Elevation",
     box = FALSE,
     axes = FALSE)

write.csv(shrubbuffer, "Data/shrubdemstats.csv")
```

